title: Selfie Filter
hero_image: images/banner.png
description: Make a selfie filter in Scratch using the Facial Recognition extension blocks
version: 1
listed: true
pdf: false
steps:
  - title: What you will make
  - title: Set up the project
  - title: Make a hat follow the top of your head
  - title: Tilt and resize your sprite
  - title: Add nose, mouth, ears, etc  
  - title: Challenge
    challenge: true
    completion:
      - external
