title: Selfie filter
hero_image: images/banner.png
description: Make a selfie filter in Scratch using the facial recognition extension blocks
version: 1
listed: false
copyedit: false
pdf: false
steps:
  - title: What you will make
  - title: Set up the project
    completion:
    - engaged
  - title: Put a hat on your head
  - title: Tilt and resize your sprite
  - title: Add more
    completion:
    - internal
  - title: Challenge
    challenge: true
    completion:
      - external
